### ISSUE TITLE
Question about rendering on server-side

### ISSUE THREAD

**Issue by andersonba** [yashmahalwal/relay-ssr#2]
Hi Yash! First of all, nice job! I read your article on Medium and that's what got me to play with your code.
I have a special question about rendering on the server-side.

> We will be rendering the app on server twice. First time, it will only be to collect all the queries for Relay. For this render, we will use a different environment. Take a moment to look at it.

Debugging your code, I added some console.log to simulate it.

![Screen Shot 2020-08-17 at 00 29 43](https://user-images.githubusercontent.com/1501013/90354896-045d7e00-e021-11ea-9bd3-192f119a4657.png)

Thinking about performance, I believe that this can affect response time and using more server resources. Do you agree?

Wouldn't it be possible to solve with just one execution?
Thanks!

**Comment by andersonba** [comment]
Another weird behavior it's if I use the `store-and-network` fetch policy:

```javascript
  const result = useQuery<pagesQuery>(query, {}, {
    fetchPolicy: 'store-and-network',
  });
```

It will request the graphql 3 times:
1. With the empty store on server (ok)
1. Second render on server, ignoring the records data (makes sense due to rerender)
1. At the browser (ok)

But I suppose it should be just 1 and 3.

**Comment by yashmahalwal** [comment]
> Another weird behavior it's if I use the `store-and-network` fetch policy:
> 
> ```js
>   const result = useQuery<pagesQuery>(query, {}, {
>     fetchPolicy: 'store-and-network',
>   });
> ```
> 
> It will request the graphql 3 times:
> 
> 1. With the empty store on server (ok)
> 2. Second render on server, ignoring the records data (makes sense due to rerender)
> 3. At the browser (ok)
> 
> But I suppose it should be just 1 and 3.

Thanks for reading the article. I am glad that you enjoyed it. Let me start by answering this one. The behaviour is as expected. If you read the article, I've written:
> In case you want to do initial rendering using store but update it later, use `store-and-network`. Here, Relay renders the app using its store. While it does that, it also sends a network request. When the network request comes in, Relay re-renders with the new data.

So with every render, a graphql request will be sent out. Meanwhile, relay will render with the old data in the store. If it was set to `store-or-network`, only one request would've been sent - the first one. That is because I make the data available on the client side by encoding and putting it into the DOM. So it won't need to send out a network request on the client side either.

**Comment by yashmahalwal** [comment]
> Hi Yash! First of all, nice job! I read your article on Medium and that's what got me to play with your code.
> I have a special question about rendering on the server-side.
> 
> > We will be rendering the app on server twice. First time, it will only be to collect all the queries for Relay. For this render, we will use a different environment. Take a moment to look at it.
> 
> Debugging your code, I added some console.log to simulate it.
> 
> ![Screen Shot 2020-08-17 at 00 29 43](https://user-images.githubusercontent.com/1501013/90354896-045d7e00-e021-11ea-9bd3-192f119a4657.png)
> 
> Thinking about performance, I believe that this can affect response time and using more server resources. Do you agree?
> 
> Wouldn't it be possible to solve with just one execution?
> Thanks!

As with almost everything in computer science, this is a trade-off. Our sole aim is to make **graphql data available before rendering.** In order to do that, you need to know where all the queries are. There are two ways to do that:
1. Write all the queries in a fixed place. That way, you will always know where they are.
2. Write queries as and when you want and then collect them before rendering.

The first way is the one suggested by next.js in their examples. You write the queries along with the pages and then use data fetching (`getStaticProps` or `getServerSideProps`). This way, your data will be available before the page renders. This is good and needs only one render on the server. I have covered that under this [commit](https://github.com/yashmahalwal/relay-ssr/tree/42dc8e690b163c1c8c24d8a654fe105a663d670e).

At my last job, one of the tasks I had was to slowly transfer the humongous frontend codebase to next.js for SSR. Our code was distributed in form of npm packages. Queries were transpiled and put in the node modules. In that case, you do not have control over where the queries are written. You will need to do a render to collect all the queries. Then you fire and wait for all the queries to return. And then you render again. [This is what relay tools suggest](https://github.com/relay-tools/react-relay-network-modern-ssr#readme).

First way: 1 render on the server, 1 render on the client
Second way: 2 renders on the server, 1 renders on the client

Overhead: An extra render
Advantage: More flexible code structure. Useful for porting older code to SSR.

If you think of it, this isn't that big of a tradeoff either. That's because in the first render, you don't wait for the network calls to finish. You simply collect the queries and discard the result.

Hope this clears things up ; )

**Comment by andersonba** [comment]
I got it, makes sense. Thanks for the explanation!
again, nice job!
